### ISSUE TITLE
Adding Vietnamese Translation

### ISSUE THREAD

**Issue by trgiangdo** [bfortuner/ml-glossary#133]
I would like to start translating your ml-glossary repo into Vietnamse and possibly contributing to both existing English and future Vietnamese versions.

Can I start my own repo and start translating like the [mlbvn/d2l-vn](https://github.com/mlbvn/d2l-vn) translation of [d2l-ai/d2l-en](https://github.com/d2l-ai/d2l-en)?

Also, I wondered if this is something already pursued by someone else?

**Comment by bfortuner** [comment]
You're welcome to! I haven't heard of any Vietnamese translation yet, so I think you're the first!

**Comment by trgiangdo** [comment]
Thank you. I'm translating in [this repo](https://github.com/trgiangdo/ml-glossary-vn) and will contribute with new content soon, hopefully.
