### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mbauman** [bfortuner/ml-glossary#51]
I see that the probability page has a [CC-BY-NC-SA license on it](https://github.com/bfortuner/ml-cheatsheet/blob/2b0ef4196d7370db5e21751fcebbe558c1e1e160/docs/probability.rst). Is that the license for the whole repository?

**Comment by tofighi** [comment]
I wish they make the license The GNU General Public License v3.0

**Comment by ivanistheone** [comment]
@tofighi  Did you mean GFDL since tutorial is more docs than code?

I'd vote for choosing as openly license as possible (e.g. CC0, CC-BY, MIT, or Apache).

**Comment by tofighi** [comment]
I would like to copy them anywhere without any limits. Therefore, **GFDL** could be a better option.

**Comment by Davide95** [comment]
Any news on that?

**Comment by bfortuner** [comment]
Sorry for the delay! MIT License. Just added it
